# -*- coding: utf-8 -*-
"""MVP_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lp3cMr3oLwv5RcdWIktNwNawfMJHhmpd
"""

#!pip install geemap



import ee
import geemap

Map = geemap.Map()
Map

import ee
import geemap.colormaps as cm
import geemap.foliumap as geemap
!pip install streamlit
import streamlit as st
import base64

# Add Earth Engine dataset
image = ee.Image('USGS/SRTMGL1_003')

# Set visualization parameters.
vis_params = {
    'min': 0,
    'max': 4000,
    'palette': ['006633', 'E5FFCC', '662A00', 'D8D8D8', 'F5F5F5'],
}

# Add Earth Engine DEM to map
Map.addLayer(image, vis_params, 'SRTM DEM')

states = ee.FeatureCollection("TIGER/2018/States")
Map.addLayer(states, {}, 'US States')

Map.draw_features

roi = ee.FeatureCollection(Map.draw_features)

selected_states = states.filterBounds(roi)

Map.addLayer(selected_states, {}, "Selected states")

soc = ee.Image('USGS/SRTMGL1_003')

bands = ['elevation']

def calculate_mean(image):
    # Select the bands of interest
    image = image.select(bands)
    # Calculate the mean value of each band for the ROI
    stats = image.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi, scale=30)
    # Return the mean values as a dictionary
    return stats

# Apply the function to the soil properties image
mean_stats = calculate_mean(soc)
# Print the mean values
print(mean_stats.getInfo())

image = ee.Image('USGS/SRTMGL1_003')
print(image.bandNames().getInfo())

